name       : mc
version    : 4.8.24
release    : 11
source     :
    - https://github.com/MidnightCommander/mc/archive/4.8.24.tar.gz : 7574a58f39d65bec52963e91adb5a76c989bfc65ad2a2bcea382d3500df9d845
license    : GPL-3.0-r-later
component  : system.utils
summary    : GNU midnight commander (ncurses based file manager)
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libssh2)
    - pkgconfig(slang)
    - pkgconfig(x11)
    - gpm-devel
description: |
    GNU Midnight Commander is a visual file manager that allows full file management using the terminal and utilizing ncurses. It allows standard features such as copying, moving, deleting, editing, and searching files.
setup      : |
    # disable helpers tests because they are failing
    sed -i 's| helpers-list||' tests/src/vfs/extfs/Makefile.am
    %autogen --disable-static \
        --enable-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
