name       : mc
version    : 4.8.19
release    : 6
source     :
    - http://ftp.midnight-commander.org/mc-4.8.19.tar.xz : eb9e56bbb5b2893601d100d0e0293983049b302c5ab61bfb544ad0ee2cc1f2df
license    : GPL-3.0
component  : system.utils
summary    : GNU midnight commander (ncurses based file manager)
builddeps  :
    - pkgconfig(libssh2)
    - pkgconfig(slang)
    - pkgconfig(x11)
    - gpm-devel
description: |
    GNU Midnight Commander is a visual file manager that allows full file management using the terminal and utilizing ncurses. It allows standard features such as copying, moving, deleting, editing, and searching files.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
